# Generated by Django 4.2.7 on 2023-11-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='file',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
    ]
