# Generated by Django 4.2.7 on 2023-11-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_file_file_alter_file_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FilePathField(path='uploads/', verbose_name='Путь до файла'),
        ),
    ]
